# Generated by Django 5.0 on 2024-01-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru_RU', models.CharField(max_length=255, null=True)),
                ('title_en_EN', models.CharField(max_length=255, null=True)),
                ('title_ky_KG', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_ru_RU', models.TextField(blank=True, null=True)),
                ('text_en_EN', models.TextField(blank=True, null=True)),
                ('text_ky_KG', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
        ),
    ]
