# Generated by Django 5.0 on 2024-01-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_text_en_en_post_text_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_kg',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_kg',
            new_name='title_ky',
        ),
    ]
