# Generated by Django 5.0 on 2024-01-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0004_rename_text_en_en_card_text_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='text_kg',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='cardsblock',
            old_name='text_kg',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='cardsblock',
            old_name='title_kg',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='sliderblock',
            old_name='text_kg',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='sliderblock',
            old_name='title_kg',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='textblock',
            old_name='text_kg',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='textblock',
            old_name='title_kg',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='textwithimageblock',
            old_name='text_kg',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='textwithimageblock',
            old_name='title_kg',
            new_name='title_ky',
        ),
    ]
