# Generated by Django 5.0 on 2024-01-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0006_footer_sociallinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='title',
        ),
        migrations.AddField(
            model_name='footer',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='footer',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='link_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AlterField(
            model_name='footer',
            name='about_us',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
