# Generated by Django 5.0 on 2024-01-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0007_remove_footer_title_footer_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='call_to_action_color',
        ),
        migrations.RemoveField(
            model_name='header',
            name='call_to_action_link',
        ),
        migrations.RemoveField(
            model_name='header',
            name='call_to_action_text',
        ),
    ]
