# Generated by Django 5.0 on 2024-01-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0008_remove_header_call_to_action_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsliderblock',
            name='direction',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1),
        ),
    ]
