# Generated by Django 5.0 on 2024-01-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0009_textsliderblock_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='footer',
            name='about_us_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_us_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_us_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
