# Generated by Django 5.0 on 2024-01-25 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0010_alter_footer_options_alter_sociallinks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='page',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='ncm_app.page'),
            preserve_default=False,
        ),
    ]
