# Generated by Django 5.0 on 2024-01-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0011_footer_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
