# Generated by Django 5.0 on 2024-01-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0012_sociallinks_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='page',
        ),
        migrations.AddField(
            model_name='header',
            name='page',
            field=models.ManyToManyField(related_name='header', to='ncm_app.page'),
        ),
    ]
