# Generated by Django 5.0 on 2024-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0013_remove_header_page_header_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='page',
        ),
        migrations.AddField(
            model_name='footer',
            name='page',
            field=models.ManyToManyField(related_name='footer', to='ncm_app.page'),
        ),
    ]
