# Generated by Django 5.0 on 2024-01-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0014_remove_footer_page_footer_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='page',
        ),
        migrations.RemoveField(
            model_name='header',
            name='page',
        ),
        migrations.AddField(
            model_name='page',
            name='footer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ncm_app.footer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ncm_app.header'),
            preserve_default=False,
        ),
    ]
