# Generated by Django 5.0 on 2024-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0016_page_title_en_page_title_ky_page_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='header',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
